disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - line_length
  - type_name
opt_in_rules: # some rules are only opt-in
  - empty_count
analyzer_rules:
  - explicit_self
force_cast: error
force_try:
  severity: error
line_length:
  warning: 300
type_body_length:
  warning: 300
file_length:
  warning: 500
nesting:
  type_level: 2
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
