excluded:
  - Pods, Products, Frameworks

# Opt-In Rules
opt_in_rules:
# Idiomatic Rules
 - discouraged_none_name
 - explicit_init
 - fatal_error_message
 - file_name_no_space
 - force_unwrapping
 - implicitly_unwrapped_optional
 - joined_default_parameter
 - legacy_multiple
 - prefer_zero_over_explicit_init
 - redundant_nil_coalescing
 - return_value_from_void_function
 - static_operator
 - toggle_bool
 - unavailable_function

# Lint Rules
 - discarded_notification_center_observer
 - identical_operands
 - overridden_super_call
 - prohibited_interface_builder
 - prohibited_super_call
 - unowned_variable_capture
 - weak_delegate
 - yoda_condition

# Metrics Rules
 - closure_body_length
 - enum_case_associated_values_count

# Performance Rules
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
 - empty_collection_literal
 - empty_count
 - empty_string
 - first_where
 - flatmap_over_map_reduce
 - last_where
 - reduce_into
 - sorted_first_last

# Style Rules
 - attributes
 - closure_end_indentation
 - closure_spacing
 - collection_alignment
 - file_header
 - implicit_return
 - indentation_width
 - let_var_whitespace
 - literal_expression_end_indentation
 - modifier_order
 - multiline_arguments
 - multiline_arguments_brackets
 - multiline_function_chains
 - multiline_literal_brackets
 - multiline_parameters
 - multiline_parameters_brackets
 - non_overridable_class_declaration
 - operator_usage_whitespace
 - optional_enum_case_matching
 - shorthand_argument
 - sorted_imports
 - trailing_closure
 - type_contents_order
 - unneeded_parentheses_in_closure_argument
 - vertical_parameter_alignment_on_call
 - vertical_whitespace_closing_braces 

# Analyzer Rules
analyzer_rules:
  - explicit_self

# Default Rule Adjustments
# Idiomatic Configuration
type_name:
  min_length:
    warning: 3
    error: 0
  max_length: 
    warning: 40
    error: 60

# Lint Configuration
blanket_disable_command:
  severity: warning
  allowed_rules: ["file_length", "type_body_length", "implicitly_unwrapped_optional"]

# Metrics Configuration
cyclomatic_complexity:
  ignores_case_statements: true
file_length:
  warning: 500
  error: 800
function_body_length:
  warning: 50
  error: 80
line_length:
  warning: 120
  error: 300
nesting:
  type_level: 2
  function_level: 3
type_body_length:
  warning: 300
  error: 450

# Style Configuration
identifier_name:
  min_length: 
    warning: 3
    error: 0
  max_length: 
    warning: 40
    error: 60
  excluded:
  - id
  - URL
  - GlobalAPIKey
  - x
  - y
multiple_closures_with_trailing_closure:
  severity: error

# Opt-In Configuration
# Idiomatic Configuration
discouraged_none_name:
  severity: warning
explicit_init:
  severity: warning
fatal_error_message:
  severity: warning
file_name_no_space:
  severity: warning
force_unwrapping:
  severity: warning
implicitly_unwrapped_optional:
  severity: warning
  mode: all
joined_default_parameter:
  severity: warning
legacy_multiple:
  severity: warning
prefer_zero_over_explicit_init:
  severity: warning
redundant_nil_coalescing:
  severity: warning
return_value_from_void_function:
  severity: warning
static_operator:
  severity: warning
toggle_bool:
  severity: warning
unavailable_function:
  severity: warning

# Lint Configuration
discarded_notification_center_observer:
  severity: warning
identical_operands:
  severity: warning
overridden_super_call:
  severity: error
prohibited_interface_builder:
  severity: error
prohibited_super_call:
  severity: error
unowned_variable_capture:
  severity: warning
weak_delegate:
  severity: warning
yoda_condition:
  severity: warning

# Metrics Configuration
closure_body_length:
  warning: 30
  error: 100
enum_case_associated_values_count:
  warning: 5
  error: 6

# Performance Configuration
contains_over_filter_count:
  severity: warning
contains_over_filter_is_empty:
  severity: warning
contains_over_first_not_nil:
  severity: warning
contains_over_range_nil_comparison:
  severity: warning
empty_collection_literal:
  severity: warning
empty_count:
  severity: warning
empty_string:
  severity: warning
first_where:
  severity: warning
flatmap_over_map_reduce:
  severity: warning 
last_where:
  severity: warning
reduce_into:
  severity: warning
sorted_first_last:
  severity: warning

# Style Configuration
attributes:
  severity: warning
  always_on_same_line: [“@NSManaged”, "@Debounced"]
closure_end_indentation:
  severity: warning
closure_spacing:
  severity: warning
collection_alignment:
  severity: warning
file_header:
  severity: warning
implicit_return:
  severity: warning
indentation_width:
  severity: warning
let_var_whitespace:
 severity: warning
literal_expression_end_indentation:
  severity: warning
modifier_order:
  severity: warning
multiline_arguments:
  severity: warning
multiline_arguments_brackets:
  severity: warning
multiline_function_chains:
  severity: warning
multiline_literal_brackets:
  severity: warning
multiline_parameters:
  severity: warning
multiline_parameters_brackets:
  severity: warning
non_overridable_class_declaration:
 severity: warning
operator_usage_whitespace:
  severity: warning
optional_enum_case_matching:
  severity: warning
shorthand_argument:
 severity: warning
sorted_imports:
  severity: warning
trailing_closure:
  severity: warning
type_contents_order:
  severity: warning
  order: [
    [SwiftLintFramework.TypeContent.case],
    [SwiftLintFramework.TypeContent.typeAlias, SwiftLintFramework.TypeContent.associatedType], 
    [SwiftLintFramework.TypeContent.subtype], 
    [SwiftLintFramework.TypeContent.typeProperty], 
    [SwiftLintFramework.TypeContent.instanceProperty], 
    [SwiftLintFramework.TypeContent.initializer],
    [SwiftLintFramework.TypeContent.deinitializer], 
    [SwiftLintFramework.TypeContent.typeMethod], 
    [SwiftLintFramework.TypeContent.viewLifeCycleMethod], 
    [SwiftLintFramework.TypeContent.otherMethod], 
    [SwiftLintFramework.TypeContent.subscript]
  ]
unneeded_parentheses_in_closure_argument:
  severity: warning
vertical_parameter_alignment_on_call:
  severity: warning
vertical_whitespace_closing_braces:
  severity: warning

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
