disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
opt_in_rules: # some rules are only opt-in
  - empty_count
analyzer_rules:
  - explicit_self
force_cast: error
force_try:
  severity: error
line_length:
  warning: 300
type_body_length:
  warning: 300
file_length:
  warning: 500
type_name:
  min_length: 3
  max_length: 
    warning: 40
    error: 60
identifier_name:
  min_length: 3
  max_length: 
    warning: 40
    error: 60
  exclude:
  - id
  - URL
  - GlobalAPIKey
nesting:
  type_level: 2
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
